[build]
  base = "/"
  command = "npm install && cd client && npm install && cd .. && npm run build"
  functions = "netlify-functions"
  publish = "client/build"
  environment = { CI = "false", SECRETS_SCAN_ENABLED = "false" }

[secrets]
  SECRETS_SCAN_ENABLED = false


[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"