[build]
  base = "/"
  command = "cd client && npm install && CI=false npm run build"
  publish = "client/build"
  environment = { CI = "false" }

[secrets]
  SECRETS_SCAN_OMIT_KEYS = ["NODE_ENV", "PORT"]
  SECRETS_SCAN_OMIT_PATHS = ["logs/**", "docs/**", "docs-archive/**", "*.md", "**/*.log", "**/*.json", "scripts/**", "client/build/**", "client/package-lock.json"]

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"