[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "npm ci --include=dev",
  "cd client && npm ci --include=dev && cd .."
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"