-- Sample data for ScottGPT schema
-- Insert after running schema.sql

-- Sample sources
INSERT INTO sources (type, title, org, location, date_start, date_end, industry_tags, summary, url) VALUES
(
    'project',
    'FedFusion.ai',
    'Independent',
    'Remote',
    '2024-02-01',
    '2025-05-30',
    ARRAY['AI/ML', 'Gov', 'Regulated'],
    'AI-powered federal contract intelligence platform with RAG, vector embeddings, multi-source enrichment.',
    'https://fedfusion.ai'
),
(
    'job',
    'Sr. Director OT Security',
    'McKesson',
    'Atlanta, GA',
    '2018-01-01',
    '2020-12-31',
    ARRAY['Cybersecurity', 'Healthcare', 'Regulated'],
    'Led operational technology security for healthcare supply chain infrastructure.',
    NULL
),
(
    'project',
    'Healthcare AI Platform',
    'McKesson',
    'Atlanta, GA',
    '2019-06-01',
    '2020-10-31',
    ARRAY['AI/ML', 'Healthcare', 'Product'],
    'Machine learning platform for supply chain optimization and predictive analytics.',
    NULL
);

-- Sample skills for normalization
INSERT INTO skills (name, aliases, category) VALUES
('Program Management', ARRAY['PM', 'PMO', 'Project Management'], 'leadership'),
('RAG', ARRAY['Retrieval Augmented Generation', 'Retrieval-Augmented Generation'], 'technical'),
('Vector Database', ARRAY['pgvector', 'Vector DB', 'Embeddings'], 'technical'),
('Cybersecurity', ARRAY['InfoSec', 'Information Security', 'Security'], 'domain'),
('Prompt Engineering', ARRAY['Prompt Design', 'LLM Engineering'], 'technical'),
('AI/ML', ARRAY['Artificial Intelligence', 'Machine Learning', 'ML'], 'technical');

-- Sample synonyms for query expansion
INSERT INTO synonyms (term, aliases) VALUES
('leadership', ARRAY['management', 'leading teams', 'team lead', 'director']),
('government', ARRAY['gov', 'federal', 'public sector', 'regulation']),
('healthcare', ARRAY['health', 'medical', 'pharma', 'clinical']),
('security', ARRAY['cybersecurity', 'infosec', 'information security']),
('ai', ARRAY['artificial intelligence', 'machine learning', 'ml', 'llm']),
('database', ARRAY['db', 'data storage', 'postgresql', 'vector db']);

-- Sample content chunks (without embeddings - these will be generated by the ingestion pipeline)
INSERT INTO content_chunks (
    source_id, 
    title, 
    content, 
    content_summary, 
    skills, 
    tags, 
    date_start, 
    date_end, 
    token_count
) VALUES
(
    1, -- FedFusion.ai
    'RAG Architecture and Compliance',
    'FedFusion.ai • AI Platform • 2024–2025 • Technical Implementation: Implemented RAG over SAM.gov, FPDS, USAspending with pgvector-backed retrieval. Generated citation-linked drafts to eliminate hallucinations and support auditability. Built multi-source data enrichment pipeline processing 500K+ federal opportunities.',
    'Built RAG system with pgvector for federal contract intelligence, eliminating hallucinations through citation-linked responses.',
    ARRAY['RAG', 'Vector Database', 'OpenAI', 'Prompt Engineering', 'Compliance'],
    ARRAY['AI Product', 'Gov', 'Proposal Automation'],
    '2024-02-01',
    '2025-05-30',
    89
),
(
    1, -- FedFusion.ai
    'Product Strategy and Market Fit',
    'FedFusion.ai • AI Platform • 2024–2025 • Business Outcomes: Achieved product-market fit with 40+ active users and $15K+ ARR. Reduced proposal writing time from 40+ hours to 4-6 hours through automated intelligence gathering and draft generation.',
    'Achieved product-market fit with 40+ users, reducing proposal writing time by 85% through AI automation.',
    ARRAY['Product Management', 'AI/ML', 'Market Research'],
    ARRAY['Product Strategy', 'SaaS', 'Gov Contracting'],
    '2024-02-01',
    '2025-05-30',
    72
),
(
    2, -- McKesson OT Security
    'OT Security Leadership',
    'McKesson • Sr. Director OT Security • 2018–2020 • Leadership: Led cross-functional teams securing operational technology across 40+ distribution centers. Developed security frameworks for healthcare supply chain critical infrastructure, ensuring FDA compliance and patient safety.',
    'Led OT security across 40+ healthcare distribution centers, developing FDA-compliant security frameworks.',
    ARRAY['Cybersecurity', 'Program Management', 'Compliance', 'Leadership'],
    ARRAY['OT Security', 'Healthcare', 'Critical Infrastructure'],
    '2018-01-01',
    '2020-12-31',
    78
),
(
    3, -- Healthcare AI Platform
    'AI Platform Development',
    'McKesson • Healthcare AI Platform • 2019–2020 • Technical Leadership: Architected machine learning platform for supply chain optimization. Implemented predictive analytics reducing inventory waste by 15% and improving delivery reliability by 22% across regional distribution network.',
    'Built ML platform reducing inventory waste 15% and improving delivery reliability 22% for healthcare supply chain.',
    ARRAY['AI/ML', 'Platform Architecture', 'Predictive Analytics'],
    ARRAY['Healthcare', 'Supply Chain', 'Platform'],
    '2019-06-01',
    '2020-10-31',
    85
);

-- Note: Embeddings will be generated and inserted by the data ingestion pipeline
-- The search_chunks function expects 1536-dimensional vectors (OpenAI ada-002 format)